var colour = "blue";
colour = "pink";
console.log(colour);
var fruit = 30;
console.log(fruit);
var present_Student = true;
console.log(present_Student);
var fristName = 'anaya';
var secondName = 'khan';
var lastName = fristName + '  ' + secondName;
console.log(lastName);
var fristclass = 'maiez';
var secondclass = 'khan';
var fullclass = "".concat(fristclass, " ").concat(secondclass);
console.log(fullclass);
var num1 = 4;
var num2 = 4;
var totalnum = (num1 + num2);
console.log(totalnum);
var cart = 8;
var cart2 = 3;
var totalnumber = (cart - cart2);
console.log(totalnumber);
var num3 = 6;
var num4 = 3;
var totalnum2 = (6 * 3);
console.log(totalnum2);
var num5 = 10;
var num6 = 2;
var totalnum3 = (10 / 2);
console.log(totalnum3);
var leyer = 5;
var apples = 8;
var power = Math.pow(apples, 2);
console.log(power);
var one = 10;
var two = 3;
var three = one % two;
console.log(three);
var A = 6;
console.log(++A);
var B = 10;
console.log(--B);
var C = 5;
var D = 2;
var E = ++C + C++ + --D + D-- + C + D++ + D;
console.log(E);
var F = 8;
console.log(F--);
var G = 10;
console.log(--G);
var result = 2 + 4 * 5;
console.log(result);
var aa = 5;
var bb = 5;
console.log(aa == bb);
var cc = 8;
var dd = 9;
console.log(cc == dd);
for (var i = 1; i <= 5; i++) {
    console.log(i);
}
